from fastapi import FastAPI, UploadFile, File, Form, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from typing import List
import json
from datetime import datetime, timezone

from .agent import app_graph
from .schemas import AnalysisResponse
from .registry import MODEL_REGISTRY, get_tool_status
from .report import generate_pdf_report
from .change_map import compute_change_baseline
from .optical_sar import verify_optical_sar_pair

app = FastAPI(title="SatQuery AI API Gateway", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Root + Health
# ---------------------------------------------------------------------------

@app.get("/")
def root():
    return {"name": "SatQuery AI", "status": "AVAILABLE", "version": "1.0.0"}


@app.get("/health")
def health_check():
    tool_status = {task: get_tool_status(task) for task in MODEL_REGISTRY.keys()}
    return {
        "api_status": "AVAILABLE",
        "specialist_endpoints_configured": any(
            v["base_url"] != "" for v in MODEL_REGISTRY.values()
        ),
        "registry_status": tool_status,
        "baseline_tools": ["change_map", "optical_sar"],
    }


# ---------------------------------------------------------------------------
# Evaluations
# ---------------------------------------------------------------------------

@app.get("/evaluations")
def get_evaluations():
    import os
    from pathlib import Path
    
    # We will read the evaluation results generated by the core evaluation framework
    benchmarks = ["vrsbench", "rsvqa", "cdvqa", "isro_sac"]
    results = []
    
    # We assume the backend is run from the project root CWD
    for b in benchmarks:
        path = Path(f"evaluation/{b}/results.json")
        if path.exists():
            with open(path, "r", encoding="utf-8") as f:
                results.append(json.load(f))
        else:
            results.append({
                "benchmark_name": b.upper(),
                "status": "NOT_CONFIGURED",
                "metrics": None,
                "expected_format": "Unknown",
                "dataset_path": "Unknown",
                "description": "Evaluation framework not yet run for this benchmark."
            })
            
    return {"evaluations": results}

# ---------------------------------------------------------------------------
# Primary Analysis
# ---------------------------------------------------------------------------

@app.post("/analyze", response_model=AnalysisResponse)
async def analyze(
    query: str = Form(...),
    parameters: str = Form("{}"),
    benchmark_mode: bool = Form(False),
    files: List[UploadFile] = File(...),
):
    try:
        params_dict = json.loads(parameters)
    except Exception:
        params_dict = {}

    file_data = [{"filename": f.filename, "bytes": await f.read()} for f in files]

    # --- Baseline shortcut for two-image tasks ---
    # When no specialist endpoint is configured, route to local baselines
    # so the prototype produces real (non-fabricated) results immediately.
    if len(file_data) == 2:
        q = query.lower()
        if any(kw in q for kw in ["change", "difference"]):
            baseline_result = compute_change_baseline(
                file_data[0]["bytes"], file_data[1]["bytes"]
            )
            if baseline_result.get("status") != "ERROR":
                baseline_result["provenance"]["inference_timestamp"] = datetime.utcnow().isoformat() + "Z"
                baseline_result["provenance"]["input_filenames"] = [f["filename"] for f in file_data]
                return AnalysisResponse(
                    task="change_analysis",
                    answer=baseline_result["answer"],
                    status=baseline_result["status"],
                    confidence=baseline_result.get("confidence"),
                    evidence=baseline_result.get("evidence", []),
                    visual_output=baseline_result.get("visual_output"),
                    execution_trace=[
                        "VALIDATED: Both files accepted.",
                        "ROUTER: Selected task 'change_analysis'.",
                        "EXECUTION: Baseline pixel-diff applied.",
                        "EVIDENCE VALIDATOR: Spatial evidence present.",
                    ],
                    provenance=baseline_result["provenance"],
                )

        if any(kw in q for kw in ["sar", "radar", "optical"]):
            baseline_result = verify_optical_sar_pair(
                file_data[0]["bytes"], file_data[1]["bytes"]
            )
            if baseline_result.get("status") != "ERROR":
                baseline_result["provenance"]["inference_timestamp"] = datetime.utcnow().isoformat() + "Z"
                baseline_result["provenance"]["input_filenames"] = [f["filename"] for f in file_data]
                return AnalysisResponse(
                    task="optical_sar",
                    answer=baseline_result["answer"],
                    status=baseline_result["status"],
                    confidence=baseline_result.get("confidence"),
                    evidence=baseline_result.get("evidence", []),
                    visual_output=baseline_result.get("visual_output"),
                    execution_trace=[
                        "VALIDATED: Both files accepted.",
                        "ROUTER: Selected task 'optical_sar'.",
                        "EXECUTION: Metadata alignment baseline applied.",
                        "EVIDENCE VALIDATOR: Metadata evidence present.",
                    ],
                    provenance=baseline_result["provenance"],
                )

    # --- Standard LangGraph agent pipeline ---
    state = {
        "query": query,
        "files": file_data,
        "parameters": params_dict,
        "benchmark_mode": benchmark_mode,
        "trace": [],
    }

    result = await app_graph.ainvoke(state)
    api_res = result.get("api_response", {})

    return AnalysisResponse(
        task=result.get("selected_task", "unknown"),
        answer=api_res.get("answer", "ERROR"),
        status=api_res.get("status", "ERROR"),
        evidence=api_res.get("evidence", []),
        visual_output=api_res.get("visual_output"),
        confidence=api_res.get("confidence"),
        execution_trace=result.get("trace", []),
        provenance=api_res.get("provenance"),
        validation=result.get("validation_results"),
    )


# ---------------------------------------------------------------------------
# Report Download
# ---------------------------------------------------------------------------

@app.post("/report")
async def download_report(
    query: str = Form(...),
    parameters: str = Form("{}"),
    benchmark_mode: bool = Form(False),
    files: List[UploadFile] = File(...),
):
    """Re-runs analysis and returns a downloadable plain-text report."""
    try:
        params_dict = json.loads(parameters)
    except Exception:
        params_dict = {}

    file_data = [{"filename": f.filename, "bytes": await f.read()} for f in files]

    state = {
        "query": query,
        "files": file_data,
        "parameters": params_dict,
        "benchmark_mode": benchmark_mode,
        "trace": [],
    }

    result = await app_graph.ainvoke(state)
    api_res = result.get("api_response", {})

    response_obj = AnalysisResponse(
        task=result.get("selected_task", "unknown"),
        answer=api_res.get("answer", "ERROR"),
        status=api_res.get("status", "ERROR"),
        evidence=api_res.get("evidence", []),
        visual_output=None,  # Omit binary from text report
        confidence=api_res.get("confidence"),
        execution_trace=result.get("trace", []),
        provenance=api_res.get("provenance"),
        validation=result.get("validation_results"),
    )

    report_bytes = generate_pdf_report(response_obj, query)
    return Response(
        content=report_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=SatQuery_Report.pdf"},
    )
